//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public string ID { get; set; }
        public string EMP_ID { get; set; }
        public string PASSWORD { get; set; }
        public string SALT { get; set; }
        public string ROLE { get; set; }
    }
}
